### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yijinjing** [adnanmunawar/matlab-rrt-variants#2]
hello, [tmp,idx] = min(connectingNodes(:,dim+2)); an error occured,why.

**Comment by adnanmunawar** [comment]
Can you paste the full error

**Comment by yijinjing** [comment]
Index exceeds matrix dimension.
error RRTstar3D>findMinimumPath (line 647)
    [tmp,idx] = min(connectingNodes(:,dim+2));

error RRTstar3D (line 131)
path = findMinimumPath(tree,end_node,dim);

error benchmarkRRT (line 149)
    [n_its path_n,run_time] = RRTstar3D(dim,segmentLength,radius,random_world,show_output,samples);

**Comment by zhangbinchao** [comment]
i have got the same error,
Attempted to access connectingNodes(:,5); index out of bounds because
size(connectingNodes)=[0,0].

Error in RRTstar3D>findMinimumPath (line 647)
    [tmp,idx] = min(connectingNodes(:,dim+2));

Error in RRTstar3D (line 136)
path_500 = findMinimumPath(tree_500,end_node,dim);

Error in benchmarkRRT (line 149)
    [n_its path_n,run_time] =
    RRTstar3D(dim,segmentLength,radius,random_world,show_output,samples);

**Comment by adnanmunawar** [comment]
Thanks for the detailed info. Can you please suggest what Matlab versions are you using?

**Comment by yijinjing** [comment]
thanks. 2017 version------------------ 原始邮件 ------------------
发件人: "Adnan Munawar"<notifications@github.com>
发送时间: 2020年3月10日(星期二) 上午10:57
收件人: "adnanmunawar/matlab-rrt-variants"<matlab-rrt-variants@noreply.github.com>;
抄送: "yijinjing"<1007275930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [adnanmunawar/matlab-rrt-variants] question (#2)



Thanks for the detailed info. Can you please suggest what Matlab versions are you using?
 
&mdash;

**Comment by adnanmunawar** [comment]
Can you verify if the latest commit solves your issue. Please note that you must specify a sample size of >= 4000.

**Comment by kourong** [comment]
> Index exceeds matrix dimension.
> error RRTstar3D>findMinimumPath (line 647)
> [tmp,idx] = min(connectingNodes(:,dim+2));
> 
> error RRTstar3D (line 131)
> path = findMinimumPath(tree,end_node,dim);
> 
> error benchmarkRRT (line 149)
> [n_its path_n,run_time] = RRTstar3D(dim,segmentLength,radius,random_world,show_output,samples);

hello，excuse me。Do you solved this problem?
