### ISSUE TITLE
三维仿真索引超出数组边界

### ISSUE THREAD

**Issue by kourong** [adnanmunawar/matlab-rrt-variants#3]
出错 RRTstar3D>findMinimumPath (line 656)
[tmp,idx] = min(connectingNodes(:,dim+2));

出错 RRTstar3D (line 145)
path_500 = findMinimumPath(tree_500,end_node,dim);

**Comment by joris997** [comment]
Same, this was mentioned in another issue which was closed by the author. However, the supposed solution of having samples >= 4000 does not solve it. Just for convenience:

`
Index in position 2 exceeds array bounds.

Error in RRTstar3D>findMinimumPath (line 653)
[tmp,idx] = min(connectingNodes(:,dim+2));

Error in RRTstar3D (line 137)
path = findMinimumPath(tree,end_node,dim);

Error in benchmarkRRT (line 149)
            [n_its path_n,run_time] =
            RRTstar3D(dim,segmentLength,radius,random_world,show_output,samples); 
`
MATLAB 2019b

**Comment by kourong** [comment]
> Same, this was mentioned in another issue which was closed by the author. However, the supposed solution of having samples >= 4000 does not solve it. Just for convenience:
> 
> `
> Index in position 2 exceeds array bounds.
> 
> Error in RRTstar3D>findMinimumPath (line 653)
> [tmp,idx] = min(connectingNodes(:,dim+2));
> 
> Error in RRTstar3D (line 137)
> path = findMinimumPath(tree,end_node,dim);
> 
> Error in benchmarkRRT (line 149)
> [n_its path_n,run_time] =
> RRTstar3D(dim,segmentLength,radius,random_world,show_output,samples);
> `
> MATLAB 2019b


I saw it, is there any other solution now? 
The version of matlab I use is 2019b

**Comment by joris997** [comment]
don't think so

**Comment by adnanmunawar** [comment]
Can you please specify more information about the arguments that you are passing to the code

**Comment by kourong** [comment]
I set samples=4000 。But still this problem。

**Comment by kourong** [comment]
> Can you please specify more information about the arguments that you are passing to the code

I set samples=4000 。But still this problem。

**Comment by adnanmunawar** [comment]
Please try the latest commit. Now the issue arises from sample being too low for RRT* to have found a path. Instead of throwing error, the code tells you that it didn't find a path but you really should be giving a high number of samples.

**Comment by kourong** [comment]
OK,I will try it ,Thank you.

**Comment by adnanmunawar** [comment]
@joris997 did you get a chance to try the latest commit out?

**Comment by joris997** [comment]
Yes, I got it to work and it's now a lot more intuitive as to what is going wrong. Thank you for the help.
